# -*- coding: utf-8 -*-
"""chatbot'.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L48igjHd3e8Ef8jrqInBYIWu4v16VdqF
"""

# Commented out IPython magic to ensure Python compatibility.
# %env OPENAI_API_KEY=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

pip install openai

from openai import OpenAI
client = OpenAI()

completion = client.chat.completions.create(
    model="gpt-4o-mini",
    messages=[
        {"role": "system", "content": "You are a helpful assistant."},
        {
            "role": "user",
            "content": "Write a haiku about recursion in programming."
        }
    ]
)

print(completion.choices[0].message)